functionId=MatchUrlTree("/v1/sales/sale_orders/12345/discount_amount","put")
assert(functionId=="1")
functionId=MatchUrlTree("/v1/sales/sale_orders/delivery_point_acception/sale_order_items/12345","put")
assert(functionId=="2")
functionId=MatchUrlTree("/v1/sales/sale_orders/customer_acception/sale_orders/12345","put")
assert(functionId=="3")
functionId=MatchUrlTree("/v1/sales/sale_orders/waiting_to_outs","get")
assert(functionId=="4")
functionId=MatchUrlTree("/v1/sales/sale_orders/waiting_to_transport_to_delivery_points","get")
assert(functionId=="5")
functionId=MatchUrlTree("/v1/storages/sales/stats","get")
assert(functionId=="6")
functionId=MatchUrlTree("/v1/sales/sale_orders/transport_to_delivery_points/sale_order_items/12345","put")
assert(functionId=="7")
functionId=MatchUrlTree("/v1/sales/sale_orders","post")
assert(functionId=="8")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345","get")
assert(functionId=="9")
functionId=MatchUrlTree("/v1/sales/sale_orders/warehouse_selections/sale_order_items/12345","post")
assert(functionId=="10")
functionId=MatchUrlTree("/v1/sales/sale_orders/candidate_selections/sale_order_items/12345","get")
assert(functionId=="11")
functionId=MatchUrlTree("/v1/sales/sale_orders","get")
assert(functionId=="12")
functionId=MatchUrlTree("/v1/sales/sale_orders/out_bolts/sale_order_items/12345","post")
assert(functionId=="13")
functionId=MatchUrlTree("/v1/sales/sale_orders/out_meters/sale_order_items/12345","post")
assert(functionId=="14")
functionId=MatchUrlTree("/v1/storages/sales/info","get")
assert(functionId=="15")
functionId=MatchUrlTree("/v1/accounts/params/12345","put")
assert(functionId=="16")
functionId=MatchUrlTree("/v1/accounts/params","get")
assert(functionId=="17")
functionId=MatchUrlTree("/v1/accounts/param","post")
assert(functionId=="18")
functionId=MatchUrlTree("/v1/accounts/param","get")
assert(functionId=="19")
functionId=MatchUrlTree("/v1/accounts/companies/12345","put")
assert(functionId=="20")
functionId=MatchUrlTree("/v1/accounts/companies/12345/invalid","put")
assert(functionId=="21")
functionId=MatchUrlTree("/v1/accounts/companies","post")
assert(functionId=="22")
functionId=MatchUrlTree("/v1/accounts/companies/12345","get")
assert(functionId=="23")
functionId=MatchUrlTree("/v1/accounts/companies","get")
assert(functionId=="24")
functionId=MatchUrlTree("/v1/accounts/staffs/12345","put")
assert(functionId=="25")
functionId=MatchUrlTree("/v1/accounts/staffs/12345/blocked","put")
assert(functionId=="26")
functionId=MatchUrlTree("/v1/accounts/staffs/12345/invalid","put")
assert(functionId=="27")
functionId=MatchUrlTree("/v1/accounts/staffs/12345/enabled","put")
assert(functionId=="28")
functionId=MatchUrlTree("/v1/accounts/staffs","post")
assert(functionId=="29")
functionId=MatchUrlTree("/v1/accounts/staffs/12345/active","put")
assert(functionId=="30")
functionId=MatchUrlTree("/v1/accounts/staffs/12345","get")
assert(functionId=="31")
functionId=MatchUrlTree("/v1/accounts/staffs","get")
assert(functionId=="32")
functionId=MatchUrlTree("/v1/accounts/staffs/code","get")
assert(functionId=="33")
functionId=MatchUrlTree("/v1/accounts/staffs/12345/password","put")
assert(functionId=="34")
functionId=MatchUrlTree("/v1/accounts/shops/12345","put")
assert(functionId=="35")
functionId=MatchUrlTree("/v1/accounts/shops/12345/invalid","put")
assert(functionId=="36")
functionId=MatchUrlTree("/v1/accounts/shops","post")
assert(functionId=="37")
functionId=MatchUrlTree("/v1/accounts/shops/simpleness","get")
assert(functionId=="38")
functionId=MatchUrlTree("/v1/accounts/shops/12345","get")
assert(functionId=="39")
functionId=MatchUrlTree("/v1/accounts/shops","get")
assert(functionId=="40")
functionId=MatchUrlTree("/v1/accounts/shops/code","get")
assert(functionId=="41")
functionId=MatchUrlTree(" /v1/accounts/customers/12345","put")
assert(functionId=="42")
functionId=MatchUrlTree(" /v1/accounts/customers/12345/invalid","put")
assert(functionId=="43")
functionId=MatchUrlTree(" /v1/accounts/customers/searching","get")
assert(functionId=="44")
functionId=MatchUrlTree(" /v1/accounts/customers","post")
assert(functionId=="45")
functionId=MatchUrlTree("/v1/accounts/customers/12345","get")
assert(functionId=="46")
functionId=MatchUrlTree(" /v1/accounts/customers","get")
assert(functionId=="47")
functionId=MatchUrlTree(" /v1/accounts/customers/key/12345","get")
assert(functionId=="48")
functionId=MatchUrlTree(" /v1/accounts/customers/code","get")
assert(functionId=="49")
functionId=MatchUrlTree(" /v1/accounts/positions","get")
assert(functionId=="50")
functionId=MatchUrlTree(" /v1/accounts/staffs/salers","get")
assert(functionId=="51")
functionId=MatchUrlTree("/v1/accounts/users/12345","put")
assert(functionId=="52")
functionId=MatchUrlTree(" /v1/accounts/users/12345/password","put")
assert(functionId=="53")
functionId=MatchUrlTree(" /v1/accounts/users/mobile/unique","get")
assert(functionId=="54")
functionId=MatchUrlTree(" /v1/accounts/users/mobile/validity","post")
assert(functionId=="55")
functionId=MatchUrlTree(" /v1/accounts/users/password/validity","post")
assert(functionId=="56")
functionId=MatchUrlTree(" /v1/accounts/users/email/validity","post")
assert(functionId=="57")
functionId=MatchUrlTree("/v1/accounts/users/12345/mobile","put")
assert(functionId=="58")
functionId=MatchUrlTree(" /v1/accounts/users/12345/email","put")
assert(functionId=="59")
functionId=MatchUrlTree("/v1/accounts/users/registration","post")
assert(functionId=="60")
functionId=MatchUrlTree("/v1/accounts/users/sign_in_as_employee","post")
assert(functionId=="61")
functionId=MatchUrlTree(" /v1/accounts/users/login_out","put")
assert(functionId=="62")
functionId=MatchUrlTree(" /v1/accounts/users/12345","get")
assert(functionId=="63")
functionId=MatchUrlTree(" /v1/accounts/users","get")
assert(functionId=="64")
functionId=MatchUrlTree("/v1/accounts/users/info","get")
assert(functionId=="65")
functionId=MatchUrlTree(" /v1/accounts/invitations","post")
assert(functionId=="66")
functionId=MatchUrlTree(" /v1/accounts/invitations/unusage","get")
assert(functionId=="67")
functionId=MatchUrlTree(" /v1/finances","get")
assert(functionId=="68")
functionId=MatchUrlTree("/v1/finances","post")
assert(functionId=="69")
functionId=MatchUrlTree(" /v1/finances/12345","put")
assert(functionId=="70")
functionId=MatchUrlTree(" /v1/finances/12345","get")
assert(functionId=="71")
functionId=MatchUrlTree("/v1/accounts/users/mobile/login","post")
assert(functionId=="72")
functionId=MatchUrlTree("/v1/accounts/customers/mobile/login","post")
assert(functionId=="73")
functionId=MatchUrlTree("/v1/wechats/users/binding","get")
assert(functionId=="74")
functionId=MatchUrlTree("/v1/sms/mobile_verification_code","post")
assert(functionId=="75")
functionId=MatchUrlTree(" /v1/grbacs/functions/12345","put")
assert(functionId=="76")
functionId=MatchUrlTree("/v1/grbacs/functions/12345/invalid","put")
assert(functionId=="77")
functionId=MatchUrlTree("/v1/grbacs/functions","get")
assert(functionId=="78")
functionId=MatchUrlTree(" /v1/grbacs/functions","post")
assert(functionId=="79")
functionId=MatchUrlTree(" /v1/grbac/functions/tree_parsing","get")
assert(functionId=="80")
functionId=MatchUrlTree("/v1/grbacs/user_roles/12345/invalid","put")
assert(functionId=="81")
functionId=MatchUrlTree(" /v1/grbacs/user_roles","post")
assert(functionId=="82")
functionId=MatchUrlTree(" /v1/grbacs/user_roles","get")
assert(functionId=="83")
functionId=MatchUrlTree(" /v1/grbacs/white_list/12345","put")
assert(functionId=="84")
functionId=MatchUrlTree("/v1/grbacs/white_list/12345/invalid","put")
assert(functionId=="85")
functionId=MatchUrlTree(" /v1/grbacs/white_list","post")
assert(functionId=="86")
functionId=MatchUrlTree(" /v1/grbacs/white_list","get")
assert(functionId=="87")
functionId=MatchUrlTree("/v1/grbacs/role_functions/12345/invalid","get")
assert(functionId=="88")
functionId=MatchUrlTree(" /v1/grbacs/role_functions","get")
assert(functionId=="89")
functionId=MatchUrlTree(" /v1/grbacs/roles/12345","put")
assert(functionId=="91")
functionId=MatchUrlTree(" /v1/grbacs/roles","post")
assert(functionId=="92")
functionId=MatchUrlTree(" /v1/grbacs/roles","get")
assert(functionId=="93")
functionId=MatchUrlTree("/v1/addresses/districts","get")
assert(functionId=="94")
functionId=MatchUrlTree(" /v1/addresses/districts/12345","get")
assert(functionId=="95")
functionId=MatchUrlTree(" /v1/addresses/cities","get")
assert(functionId=="96")
functionId=MatchUrlTree(" /v1/addresses/cities/12345","get")
assert(functionId=="97")
functionId=MatchUrlTree(" /v1/addresses/provinces","get")
assert(functionId=="98")
functionId=MatchUrlTree(" /v1/addresses/province/12345","get")
assert(functionId=="99")
functionId=MatchUrlTree(" /v1/addresses/streets","get")
assert(functionId=="100")
functionId=MatchUrlTree(" /v1/addresses/street/12345","get")
assert(functionId=="101")
functionId=MatchUrlTree("/v1/storages/warehouses","get")
assert(functionId=="102")
functionId=MatchUrlTree(" /v1/storages/warehouses/simpleness","get")
assert(functionId=="103")
functionId=MatchUrlTree("/v1/storages/warehouses/12345","get")
assert(functionId=="104")
functionId=MatchUrlTree(" /v1/storages/warehouses/12345","put")
assert(functionId=="105")
functionId=MatchUrlTree("/v1/storages/warehouses/12345/invalid","put")
assert(functionId=="106")
functionId=MatchUrlTree(" /v1/storages/warehouses","post")
assert(functionId=="107")
functionId=MatchUrlTree(" /v1/storages/warehouses/code","get")
assert(functionId=="108")
functionId=MatchUrlTree(" /v1/storages/areas/12345","put")
assert(functionId=="109")
functionId=MatchUrlTree(" /v1/storages/areas/12345/invalid","put")
assert(functionId=="110")
functionId=MatchUrlTree(" /v1/storages/areas","get")
assert(functionId=="111")
functionId=MatchUrlTree(" /v1/storages/areas/12345","get")
assert(functionId=="112")
functionId=MatchUrlTree(" /v1/storages/areas","post")
assert(functionId=="113")
functionId=MatchUrlTree(" /v1/storages/fabric_sample_inventory/xlsx","get")
assert(functionId=="114")
functionId=MatchUrlTree("/v1/storages/fabric_sample_inventory/xlsx","post")
assert(functionId=="115")
functionId=MatchUrlTree(" /v1/storages/fabric_patterns/satisfaction","get")
assert(functionId=="116")
functionId=MatchUrlTree("/v1/storages/fabric_pattern","get")
assert(functionId=="117")
functionId=MatchUrlTree("/v1/storages/fabric_sample/12345","put")
assert(functionId=="118")
functionId=MatchUrlTree(" /v1/storages/fabric_sample/12345","get")
assert(functionId=="119")
functionId=MatchUrlTree("/v1/storages/stats","get")
assert(functionId=="120")
functionId=MatchUrlTree(" /v1/storages/stats/12345","get")
assert(functionId=="121")
functionId=MatchUrlTree(" /v1/storages/inventories/12345","get")
assert(functionId=="122")
functionId=MatchUrlTree(" /v1/storages/dyelot_nos","get")
assert(functionId=="123")
functionId=MatchUrlTree(" /v1/storages/warehouses/fabric_inbound","post")
assert(functionId=="124")
functionId=MatchUrlTree(" /v1/storages/fabric_sample_inventories/out_bolts","post")
assert(functionId=="125")
functionId=MatchUrlTree(" /v1/storages/shelves/12345","put")
assert(functionId=="126")
functionId=MatchUrlTree(" /v1/storages/shelves/12345/invalid","put")
assert(functionId=="127")
functionId=MatchUrlTree("/v1/storages/shelves","post")
assert(functionId=="128")
functionId=MatchUrlTree("/v1/storages/shelves","get")
assert(functionId=="129")
functionId=MatchUrlTree(" /v1/storages/shelves/12345","get")
assert(functionId=="130")
functionId=MatchUrlTree("/v1/products/fabric_patterns/12345","put")
assert(functionId=="131")
functionId=MatchUrlTree("/v1/products/color_pattern_relationships/searching","get")
assert(functionId=="133")
functionId=MatchUrlTree("/v1/products/fabric_patterns/importing","post")
assert(functionId=="134")
functionId=MatchUrlTree("/v1/products/fabric_patterns","post")
assert(functionId=="135")
functionId=MatchUrlTree("/v1/products/fabric_patterns/max","get")
assert(functionId=="136")
functionId=MatchUrlTree(" /v1/products/fabric_patterns","get")
assert(functionId=="137")
functionId=MatchUrlTree("/v1/products/fabric_pattern/xlsx","get")
assert(functionId=="138")
functionId=MatchUrlTree("/v1/products/fabric_patterns/searching","get")
assert(functionId=="139")
functionId=MatchUrlTree(" /v1/products/colors/searching","get")
assert(functionId=="140")
functionId=MatchUrlTree("/v1/products/colors/company_colors","get")
assert(functionId=="141")
functionId=MatchUrlTree("/v1/products/fabric_patterns/12345","get")
assert(functionId=="142")
functionId=MatchUrlTree("/v1/sales/sale_orders/wechatNativePay/12345","post")
assert(functionId=="143")
functionId=MatchUrlTree(" /v1/sales/sale_orders/monitor_pay/12345","get")
assert(functionId=="144")
functionId=MatchUrlTree("/v1/sales/sale_orders/offline_pay/12345","post")
assert(functionId=="145")
functionId=MatchUrlTree("/v1/wechats/official_accounts","get")
assert(functionId=="146")
functionId=MatchUrlTree("/v1/storages/fabric_patterns/warehouses/12345/searching","get")
assert(functionId=="147")
functionId=MatchUrlTree(" /v1/storages/fabric_patterns/areas/12345/searching","get")
assert(functionId=="148")
functionId=MatchUrlTree("/v1/pictures/upload_token","get")
assert(functionId=="149")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/delivery_points_shop","put")
assert(functionId=="150")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/deposit","put")
assert(functionId=="151")
functionId=MatchUrlTree(" /v1/sales/sale_orders/12345/delete_sale_order_items","put")
assert(functionId=="152")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/add_sale_order_item","put")
assert(functionId=="153")
functionId=MatchUrlTree(" /v1/accounts/shops/next_code","get")
assert(functionId=="154")
functionId=MatchUrlTree("/v1/finances/finance_accounts/next_code","get")
assert(functionId=="155")
functionId=MatchUrlTree(" /v1/storages/warehouses/next_code","get")
assert(functionId=="156")
functionId=MatchUrlTree("/v1/wechats/12345/message_template","post")
assert(functionId=="158")
functionId=MatchUrlTree("/v1/storages/warehouses/godown_entries/12345","get")
assert(functionId=="159")
functionId=MatchUrlTree("/v1/sales/sale_orders/weighted/sale_order_items/12345","put")
assert(functionId=="160")
functionId=MatchUrlTree("/v1/sales/sale_orders/sale_order_items/12345/desc","put")
assert(functionId=="161")
functionId=MatchUrlTree("/v1/sales/sale_orders/sale_order_items/12345/unit_price","put")
assert(functionId=="162")
functionId=MatchUrlTree("/v1/sales/sale_orders/sale_order_items/12345/amount","put")
assert(functionId=="163")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/invalid","put")
assert(functionId=="164")
functionId=MatchUrlTree("/v1/finances/finance_accounts","post")
assert(functionId=="165")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/printing","get")
assert(functionId=="166")
functionId=MatchUrlTree("/v1/finances/finance_accounts/12345","put")
assert(functionId=="167")
functionId=MatchUrlTree("/v1/wechats/12345/payparams","post")
assert(functionId=="168")
functionId=MatchUrlTree("/v1/wechats/12345/payparams","get")
assert(functionId=="169")
functionId=MatchUrlTree("/v1/sales/sale_orders/customer/mobile","get")
assert(functionId=="170")
functionId=MatchUrlTree("/v1/sales/sale_orders/mobile/12345","get")
assert(functionId=="171")
functionId=MatchUrlTree("/v1/accounts/customers/xlsx","post")
assert(functionId=="172")
functionId=MatchUrlTree("/v1/products/fabric_patterns/code","get")
assert(functionId=="173")
functionId=MatchUrlTree("/v1/products/fabric_patterns/xlsx","post")
assert(functionId=="174")
functionId=MatchUrlTree("/v1/products/color_pattern_relationships/xlsx","post")
assert(functionId=="175")
functionId=MatchUrlTree("/v1/products/color_pattern_relationships/xlsx","get")
assert(functionId=="176")
functionId=MatchUrlTree("/v1/storages/xlsx","get")
assert(functionId=="177")
functionId=MatchUrlTree("/v1/accounts/customers/xlsx","get")
assert(functionId=="178")
functionId=MatchUrlTree("/v1/storages/return_orders/sale_returns","post")
assert(functionId=="179")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/deposit_return","put")
assert(functionId=="180")
functionId=MatchUrlTree("/v1/storages/return_orders/sale_returns/12345","get")
assert(functionId=="181")
functionId=MatchUrlTree("/v1/storages/return_orders/sale_returns/done/12345","post")
assert(functionId=="182")
functionId=MatchUrlTree("/v1/storages/return_orders/sale_returns","get")
assert(functionId=="183")
functionId=MatchUrlTree(" /v1/sales/sale_orders/day_stat","get")
assert(functionId=="184")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/discount/sale_order_items","put")
assert(functionId=="185")
functionId=MatchUrlTree(" /v1/storages/warehouses/12345/stats","get")
assert(functionId=="186")
functionId=MatchUrlTree("/v1/finances/finance_accounts","get")
assert(functionId=="187")
functionId=MatchUrlTree("/v1/storages/xlsx","post")
assert(functionId=="188")
functionId=MatchUrlTree("/v1/sales/sale_orders/modify_inventory_stat_amount","post")
assert(functionId=="189")
functionId=MatchUrlTree("/v1/storages/warehouses/godown_entries","get")
assert(functionId=="190")
functionId=MatchUrlTree("/v1/storages/customer_return_orders","post")
assert(functionId=="191")
functionId=MatchUrlTree("/v1/storages/customer_return_orders","get")
assert(functionId=="192")
functionId=MatchUrlTree("/v1/storages/customer_return_orders/12345","get")
assert(functionId=="193")
functionId=MatchUrlTree("/v1/storages/customer_return_orders/12345/cancelled_order","put")
assert(functionId=="194")
functionId=MatchUrlTree("/v1/storages/customer_return_orders/12345/printing","get")
assert(functionId=="195")
functionId=MatchUrlTree("/v1/storages/customer_return_orders/12345/return_money","put")
assert(functionId=="196")
functionId=MatchUrlTree("/v1/storages/customer_return_orders/12345/confirm_return_into_warehouse","put")
assert(functionId=="197")
functionId=MatchUrlTree("/v1/sales/sale_orders/production_sale","get")
assert(functionId=="198")
functionId=MatchUrlTree("/v1/sales/sale_orders/customer_sale/12345","get")
assert(functionId=="199")
functionId=MatchUrlTree("/v1/sales/sale_orders/customer_sales","get")
assert(functionId=="200")
functionId=MatchUrlTree("/v1/sales/sale_orders/sale_tendency","get")
assert(functionId=="201")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/balance_return","put")
assert(functionId=="202")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/cancel_cut_sale_order_items","put")
assert(functionId=="203")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/cut_sale_order_items","put")
assert(functionId=="204")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/stat_finance_account_revenue","get")
assert(functionId=="205")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_company_rels/next_code","get")
assert(functionId=="206")
functionId=MatchUrlTree("/v1/finances/finance_daily_revenues/12345/invalid","put")
assert(functionId=="207")
functionId=MatchUrlTree("/v1/finances/finance_daily_revenues","get")
assert(functionId=="208")
functionId=MatchUrlTree("/v1/finances/finance_daily_revenues/12345","get")
assert(functionId=="209")
functionId=MatchUrlTree("/v1/finances/finance_daily_revenues/types","put")
assert(functionId=="210")
functionId=MatchUrlTree("/v1/finances/finance_daily_revenues","post")
assert(functionId=="211")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_company_rels","post")
assert(functionId=="212")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_company_rels/12345","put")
assert(functionId=="213")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_company_rels","get")
assert(functionId=="214")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_company_rels/searching","get")
assert(functionId=="215")
functionId=MatchUrlTree("/v1/finances/finance_daily_revenues/types","get")
assert(functionId=="216")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors","post")
assert(functionId=="217")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors","get")
assert(functionId=="218")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors/12345","put")
assert(functionId=="219")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors/12345/invalid","put")
assert(functionId=="220")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors/template","get")
assert(functionId=="221")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors/template","post")
assert(functionId=="222")
functionId=MatchUrlTree("/v1/sales/sale_orders/sale_order_items/picking_tables","get")
assert(functionId=="223")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_production_notifications","post")
assert(functionId=="224")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_production_notifications/12345","put")
assert(functionId=="225")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_production_notifications/12345","get")
assert(functionId=="226")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_production_notifications","get")
assert(functionId=="227")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_production_notifications/12345/invalid","put")
assert(functionId=="228")
functionId=MatchUrlTree("/v1/dye_factories/dye_factory_colors/search","get")
assert(functionId=="229")
functionId=MatchUrlTree("/v1/sales/sale_orders/tag/sale_order_items/12345","put")
assert(functionId=="230")
functionId=MatchUrlTree("/v1/sales/tags","get")
assert(functionId=="231")
functionId=MatchUrlTree("/v1/sales/tags","put")
assert(functionId=="232")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/customer","put")
assert(functionId=="233")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/count_small_amount","put")
assert(functionId=="234")
functionId=MatchUrlTree("/v1/storages/warehouses/godown_entry/12345/invalid","put")
assert(functionId=="235")
functionId=MatchUrlTree("/v1/finances/account_journals/exporting","get")
assert(functionId=="236")
functionId=MatchUrlTree("/v1/accounts/customers/mobile","get")
assert(functionId=="237")
functionId=MatchUrlTree("/v1/finances/finance_accounts/12345/status","put")
assert(functionId=="238")
functionId=MatchUrlTree("/v1/finances/account_journals","get")
assert(functionId=="239")
functionId=MatchUrlTree("/v1/finances/finance_accounts/12345/transfer_accounts","put")
assert(functionId=="240")
functionId=MatchUrlTree("/v1/finances/finance_accounts/12345","get")
assert(functionId=="241")
functionId=MatchUrlTree("/v1/accounts/customers/mini-apps-login","get")
assert(functionId=="242")
functionId=MatchUrlTree("/v1/wechats/mini-apps/user/binding","get")
assert(functionId=="243")
functionId=MatchUrlTree("/v1/finances/finance_accounts/12345/exclude_money","put")
assert(functionId=="244")
functionId=MatchUrlTree("/v1/products/cargo_carriers","post")
assert(functionId=="245")
functionId=MatchUrlTree("/v1/products/cargo_carriers/next_code","get")
assert(functionId=="246")
functionId=MatchUrlTree("/v1/products/cargo_carriers","get")
assert(functionId=="247")
functionId=MatchUrlTree("/v1/products/cargo_carriers/12345","put")
assert(functionId=="248")
functionId=MatchUrlTree("/v1/products/cargo_carriers/12345","get")
assert(functionId=="249")
functionId=MatchUrlTree("/v1/accounts/param/company/unit","put")
assert(functionId=="250")
functionId=MatchUrlTree("/v1/products/fabric_patterns/12345/cargo_carriers","put")
assert(functionId=="252")
functionId=MatchUrlTree("/v1/products/fabric_patterns/12345/baseinfo","put")
assert(functionId=="253")
functionId=MatchUrlTree("/v1/products/fabric_patterns/12345/colors","put")
assert(functionId=="254")
functionId=MatchUrlTree("/v1/sales/sale_orders/sale_order_items/12345/unit_type","put")
assert(functionId=="255")
functionId=MatchUrlTree("/v1/sales/sale_orders/daily_board","get")
assert(functionId=="256")
functionId=MatchUrlTree("/v1/storages/warehouses/product_stat","get")
assert(functionId=="257")
functionId=MatchUrlTree("/v1/storages/warehouses/product_stat/12345/colors","get")
assert(functionId=="258")
functionId=MatchUrlTree("/v1/sales/sale_orders/fabric_pattern/12345/colors","get")
assert(functionId=="259")
functionId=MatchUrlTree("/v1/sales/sale_orders/fabric_pattern/12345/customer","get")
assert(functionId=="260")
functionId=MatchUrlTree("/v1/sales/sale_orders/customer/12345/fabric_pattern","get")
assert(functionId=="261")
functionId=MatchUrlTree("/v1/sales/sale_orders/12345/sale_order_items/12345","get")
assert(functionId=="262")
functionId=MatchUrlTree("/v1/finances/receipts/12345/invalid","put")
assert(functionId=="263")
functionId=MatchUrlTree("/v1/finances/receipt-types","post")
assert(functionId=="264")
functionId=MatchUrlTree("/v1/finances/receipts/12345/desc","put")
assert(functionId=="265")
functionId=MatchUrlTree("/v1/finances/receipts/12345/receipt_items/12345/desc","put")
assert(functionId=="266")
functionId=MatchUrlTree("/v1/finances/receipts","post")
assert(functionId=="267")
functionId=MatchUrlTree("/v1/finances/receipts/12345","get")
assert(functionId=="268")
functionId=MatchUrlTree("/v1/finances/receipts","get")
assert(functionId=="269")
functionId=MatchUrlTree("/v1/finances/receipt-types","get")
assert(functionId=="270")